### ISSUE TITLE
Archive this repository?

### ISSUE THREAD

**Issue by DilumAluthge** [chriselrod/SIMDPirates.jl#15]
Since this package is now deprecated, it might be worth archiving this GitHub repository? 

https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/archiving-repositories

Just FYI, if you do archive this repo, I would recommend first closing this issue. Once you have archived the repo, you can't close/open issues.

**Comment by DilumAluthge** [comment]
Bump @chriselrod

**Comment by chriselrod** [comment]
I'll do so once I've helped all of these libraries transitioned off of SIMDPirates:
https://juliahub.com/ui/Packages/SIMDPirates/jEO2E/0.8.26?t=2
I probably should've done that over the break.

**Comment by ffevotte** [comment]
Ah yes, transitioning AccurateArithmetic.jl off of SIMDPirates was also in my TODO list for the holidays... but I did not even take the time to start looking at it :/

Since AccurateArithmetic already depends on VectorizationBase, I was (maybe naively) expecting the transition to be relatively smooth, but maybe I was too optimistic? In any case, my plan was to try and list everything we use from SIMDPirates in a first step. Then identify possible replacements in the VectorizationBase API. Does that sound like it would be the way to go?

In any case, I'm not expecting to have much time to start looking at it this week, but I'll try to start looking at this transition maybe next week-end.

**Comment by chriselrod** [comment]
> Since AccurateArithmetic already depends on VectorizationBase, I was (maybe naively) expecting the transition to be relatively smooth, but maybe I was too optimistic? Then identify possible replacements in the VectorizationBase API. Does that sound like it would be the way to go?

It should be relatively smooth. I'd be happy to make a PR, as I'm obviously most familiar with the changes from SIMDPirates -> VectorizationBase. The biggest changes are:
1. `SVec` is now just `Vec`
2.  `evadd` and `evmul` are now just `vadd` and `vmul`.

There were also changes in `vload`/`vstore!`.

I'm also strongly considering making the regular base instructions not apply fast flags, and instead defining `Base.FastMath.*_fast` functions. I'm in favor of that change, it'd just require going through the library and issuing a breaking release.
Then I'd have LoopVectorization apply fast math by default, but add a key word argument to not do so.

I'm also strongly tempted to split `Vec <: Real` into `UnsignedVec <: Unsigned`, `SignedVec <: Signed`, and `FloatVec <: AbstractFloat`.
[MultiFloats](https://github.com/dzhang314/MultiFloats.jl) once required that it contain `AbstractFloats`, but that restrictions recently been lifted. But more generally, those two changes should make it easier to have `Vec`s work as expected in generic code.

If this happened first, we could use nicer `+`/`*`.
