### ISSUE TITLE
does `load` replace `vload`

### ISSUE THREAD

**Issue by JeffreySarnoff** [chriselrod/SIMDPirates.jl#4]
I had been using `vload` (broadcasted as `vload.(..)`) [here](https://github.com/JuliaMath/AccurateArithmetic.jl/blob/master/src/Summation.jl).  Is it correct and best to replace this use of `vload.(_)` with `load.(_)`? lines 47, 55, 64

**Comment by ffevotte** [comment]
At least it does not seem to cause any regression in performance.

**Comment by chriselrod** [comment]
Yes, that is correct. Sorry about dropping that breaking change.

I had separate functions for `load`/`store!` (scalar) and `vload`/`vstore!` (vector).

I've now unified them so that input types determine behavior. The new intended API is discussed in the README (there was an accidental regression in that API, [fixed here](https://github.com/JuliaRegistries/General/pull/9988)).
I now think I should have chosen to combine them under the `v-` name instead so that I don't break nearly as much code.

 I should start developing unit tests and add that so I can avoid breaking it in the future.

**Comment by JeffreySarnoff** [comment]
I agree that `vload / vstore` are better names as they encompass scalar action whereas it is unclear that `load / store` would encompass vector action (and indeed it is a near anti-pattern in Julia to automatically handle vector input through a usually scalar function).  Why not change the names now, before people have integrated the revised names?

**Comment by chriselrod** [comment]
Hmm. Okay. I'll switch to `vload`/`vstore!`.

**Comment by chriselrod** [comment]
Thanks for the report, and feel free to let me know if there are any further problems, or if you have any API suggestions.
