### ISSUE TITLE
vifelse for scaler inputs

### ISSUE THREAD

**Issue by AStupidBear** [chriselrod/SIMDPirates.jl#8]
I see you define `vifelse`  for scaler inputs using short-circuit but not `ifelse`. Why?

https://github.com/chriselrod/SIMDPirates.jl/blob/c5567caecb9fecc19f6502192aed95d1c0909b19/src/conditionals.jl#L71

In https://github.com/FluxML/NNlib.jl/pull/199, I use `vifelse` inside activation functions, but that will cause gradient inference issues. I have to overload `vifelse` to be `ifelse` for scaler cases.

**Comment by chriselrod** [comment]
I don't have a strong preference. IIRC, the reason was some combination of the compiler being able to turn branches into `select` statemetns when necessary, and that this would let you use `vifelse(::Bool,...)` with out of bounds memory accesses.

I'm using `ifelse` now, as `vifelse(::Mask, ...)` won't protect you from out of bounds memory accesses (you'd need the specific masked loads and stores) and for consistency's sake.

**Comment by AStupidBear** [comment]
@chriselrod Could you tag a new release so I can remove that line in FluxML/NNlib.jl#199 ?

**Comment by chriselrod** [comment]
https://github.com/JuliaRegistries/General/pull/14496#event-3320218608
